update setup/uninstall

diff --git a/uninstall b/uninstall
--- a/uninstall
+++ b/uninstall
@@ -1,26 +1,31 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-# === Setup SSI ===
+prepare_installer() {
+  echo "Initializing installer..."
+  SSI_VERSION="0.1.8"
 
-echo "Initializing installer..."
-tmpdir="$(mktemp -d)"
-trap 'rm -rf "$tmpdir"' EXIT
-cd "$tmpdir"
-export PATH="$tmpdir:$PATH"
+  # Set up tmp dir where all work is done
+  tmpdir="$(mktemp -d)"
+  trap 'rm -rf "$tmpdir"' EXIT
+  cd "$tmpdir"
+  export PATH="$tmpdir:$PATH"
 
-if command -v wget >/dev/null 2>&1; then
-  wget -q -O ssi https://github.com/DannyBen/ssi/releases/download/v0.1.3/ssi
-elif command -v curl >/dev/null 2>&1; then
-  curl -fsSL https://github.com/DannyBen/ssi/releases/download/v0.1.3/ssi -o ssi
-else
-  echo "Error: please install wget or curl, then try again" >&2
-  exit 1
-fi
-chmod +x ssi
+  # Download ssi if needed
+  if ! command -v ssi >/dev/null 2>&1 || [ "$(ssi --version 2>/dev/null)" != "$SSI_VERSION" ]; then
+    if command -v curl >/dev/null 2>&1; then
+      curl -fSsL https://github.com/DannyBen/ssi/releases/download/v$SSI_VERSION/ssi -o ssi
+    elif command -v wget >/dev/null 2>&1; then
+      wget -nv -O ssi https://github.com/DannyBen/ssi/releases/download/v$SSI_VERSION/ssi
+    else
+      echo "Error: please install wget or curl, then try again" >&2
+      exit 1
+    fi
+    chmod +x ssi
+  fi
+}
 
-# === Uninstall ===
-
+prepare_installer
 ssi log info Uninstalling opcode
 ssi uninstall bin op
 ssi uninstall man op.1
